
var:
  server: 120.27.226.95
  server-test: 47.98.222.182

  server-db: 121.196.200.218  #正式 数据库ip 主
  server-db-inner: 172.16.27.254 #正式 数据库ip 主（内网）

  elas-server: 121.196.200.218 #搜索引擎
  elas-server-inner: 172.16.27.254

  redis-server: 47.99.113.43
  redis-server-inner: 172.16.28.1

  appName: jinshang-server

server:
  context-path: /${var.appName}
  port: 8080
spring:
  application:
    name: ${var.appName}
  profiles:
    active: dev
  main:
    web-environment: true
  http:
    multipart:
      enabled: false
  redis:
    host: ${var.redis-server-inner}
    port: 6379
    password: 503149
    database: 1
  session:
    store-type: redis
  jackson:
    time-zone: GMT+8
  aop:
    auto: true
    proxy-target-class: true
  cache:
    type: redis

  devtools:
      restart:
        enabled: true
#  elasticsearch:
#    jest:
#      uris: http://47.98.222.182:12040
#  data:
#    elasticsearch:
#      cluster-nodes: 47.98.222.182:12041

#eureka:
# client:
#   service-url:
#    defaultZone: http://${var.server}:12800/eureka
# instance:
#   prefer-ip-address: true



logging:
  file: /root/${var.appName}/console.log
  level:
      project.jinshang: debug
      mizuki.project.core: info



project:
  projectStaticPre: http://
  staticResVersion: 1.0.0
  projectDomain: http://www.jinshang9.com/jinshang-server
  projectDomainMain: http://www.jinshang9.com
  projectPath: /root/${var.appName}
  iconfontPath: http://
  forceNginxHttps: true

mybatis:
  pgsql1:
    url: jdbc:postgresql://${var.server-db-inner}:5432/jinshang


mod:
  sms_dayu:
    accessKey: LTAI2FyqdxYpcBvF
    accessKeySecret: J41OqO0qj9s7a8rSiHMElkuXg9Hoau
    signName: 紧商网
    templateCode: SMS_150173096
  oss_ali:
#    accessKey: LTAIJkBUMwwBJ5ur
#    accessKeySecret: mvFFxILHpMj62iEcuU6B4tahXykV9q
#    endpoint: http://oss-cn-hangzhou.aliyuncs.com
#    bucketName: jinshang-hz
#    arn: acs:ram::1700049709813846:role/ossapp
#    region: oss-cn-hangzhou
    accessKey: LTAI2FyqdxYpcBvF
    accessKeySecret: J41OqO0qj9s7a8rSiHMElkuXg9Hoau
    endpoint: http://oss-cn-hangzhou.aliyuncs.com
    bucketName: jinshang9-hz
    arn: acs:ram::1330924279368455:role/ossapp
    region: oss-cn-hangzhou
  wechat:
    pay:
      appId: wx6eb2a1213254a1df
      mchId: 1404137702
      mchKey: ideD329DEDiom093l4dx94elkjo5Dv63
      subAppId:
      subMchId:
      keyPath: /root/jinshang-server/wx/apiclient_cert.p12
      mpAppId: wx83a0454391fc2d5f

#      keyPath: /Users/ycj/Downloads/WEIXINcert/apiclient_cert.p12
    login:  #微信登录web端
      appId: wx3e4de0fae28317d3
      appSecret: d9515d90025aac05da85c8e05acd9652
      accsstokenUrl: https://api.weixin.qq.com/sns/oauth2/access_token?appid=APPID&secret=SECRET&code=CODE&grant_type=authorization_code
      globalAccsstokenUrl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=APPSECRET
      wxacctokUrlTinyProg: https://api.weixin.qq.com/sns/jscode2session?appid=APPID&secret=SECRET&js_code=JSCODE&grant_type=authorization_code
      jsapiTicketUrl: https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token=ACCESS_TOKEN&type=jsapi
      wxinfoUrl: https://api.weixin.qq.com/sns/userinfo?access_token=ACCESS_TOKEN&openid=OPENID
      wapAppId: wx6eb2a1213254a1df #微信公众号
      wapAppSecret: e349883ee40b7521390f07f5158c164f
      tinyProgAppId: wx83a0454391fc2d5f
      tinyProgSecret: 3b03e15f4d2739aa5e20861018da9302
  middleware:
#    serverurl: http://new.jinshang9.com/jinshang-middleware-test
    serverurl: http://jinshang-middleware.jinshang9.com:8081/jinshang-middleware
    aozhanurl: http://aozhan-middleware.jinshang9.com:8082/aozhan-middleware
  es:
    ip: ${var.elas-server-inner}
    port: 12040

pagehelper:
  reasonable: false
  support-methods-arguments: true
  helper-dialect: postgresql
  params: count=countSql



shop:
  self-support:
    id: 8095|5623|109|107  #自营店id
  productstore-check:
    id: 109|4964|5854|5659|13780|17365|5996|107|8282    #推送紧商中间件店铺id  #库存盘点卖家id
  orders-syn:
    id: 107|108|109|8095|5623 #订单推送商家id
  aozhan-syn:
      id: 6700
  jinshang-store-url: http://122.224.247.86:18080/GwallServices/httpService?appkey=app_wms&service=subGetOrderFullLinkInfo&format=Json&secret=null&encrypt=0&content={%22orderCode%22:%22#orderno#-jinshang%22}
  aozhan-store-url: http://aozhan-middleware.jinshang9.com:8082/aozhan-middleware/aoZhan/selectOrderOperatingStatus?orderNo=#orderno#

#文件上传路径
upload:
  dir:
    moduleIcon: /Users/wyh/Downloads


---

spring:
  profiles: dev
  # 为了测试用区别 eureka service
  application:
    name: ${var.appName}-dev
  redis:
      host: ${var.redis-server}
      port: 6379
      password: 503149
      database: 9

#eureka:
# client:
#   service-url:
#    defaultZone: http://${var.server-test}:12800/eureka/
# instance:
#   prefer-ip-address: true




mybatis:
  pgsql1:
    url: jdbc:postgresql://${var.server-test}:5432/jinshang_dev7 #snap20180330
    username: admin_jinshang_dev
    password: admin04131

mod:
  wechat:
    pay:
      keyPath: /root/docker-app/jinshang-server/wx/apiclient_cert.p12
  middleware:
#    serverurl: http://new.jinshang9.com/jinshang-middleware-test
    serverurl: http://47.98.222.182/jinshang-middleware-test
    aozhanurl: http://47.98.222.182/aozhan-middleware-test
#    aozhanurl: http://localhost:9090/aozhan-middleware-test
  es:
    ip: ${var.server-test}
    port: 12040

shop:
  self-support:
    id: 8095|5623|109|107  #自营店id
  productstore-check:
    id: 109|4964|5854|5659|13780|17365|5996|107|8282   #库存盘点卖家id
  orders-syn:
    id: 107|108|109|8095|5623 #订单推送商家id
  aozhan-syn:
      id: 17944|6700
  jinshang-store-url: http://122.224.247.86:18080/GwallServices/httpService?appkey=app_wms&service=subGetOrderFullLinkInfo&format=Json&secret=null&encrypt=0&content={%22orderCode%22:%22#orderno#-jinshang%22}
  aozhan-store-url: http://47.98.222.182/aozhan-middleware/aoZhan/selectOrderOperatingStatus?orderNo=#orderno#
  #aozhan-store-url: http://120.27.226.95/aozhan-middleware/aoZhan/selectOrderOperatingStatus?orderNo=#orderno#




---
#测试环境
server:
  context-path: /${var.appName}
  port: 8080

spring:
  profiles: test
  # 为了测试用区别 eureka service
  application:
    name: ${var.appName}-test
  redis:
    host: ${var.redis-server}
    port: 6379
    password: 503149
    database: 5

#eureka:
# client:
#   service-url:
#    defaultZone: http://${var.server-test}:12800/eureka
# instance:
#   prefer-ip-address: true


shop:
  self-support:
    id: 8095|5623|109|107  #自营店id
  productstore-check:
    id: 109|4964|5854|5659|13780|17365|5996|107|8282   #库存盘点卖家id
  orders-syn:
    id: 107|108|109|8095|5623 #订单推送商家id
  aozhan-syn:
    id: 17944
  jinshang-store-url: http://122.224.247.86:18080/GwallServices/httpService?appkey=app_wms&service=subGetOrderFullLinkInfo&format=Json&secret=null&encrypt=0&content={%22orderCode%22:%22#orderno#-jinshang%22}
  aozhan-store-url: http://47.98.222.182/aozhan-middleware-test/aoZhan/selectOrderOperatingStatus?orderNo=#orderno#

mod:
  middleware:
    serverurl: http://47.98.222.182/jinshang-middleware-test
    aozhanurl: http://47.98.222.182/aozhan-middleware-test
  es:
    ip: ${var.server-test}
    port: 12040


mybatis:
  pgsql1:
    url: jdbc:postgresql://${var.server-test}:5432/jinshang_dev7
    username: admin_jinshang_dev
    password: admin04131




